services:
  # Servicio Web - Backend FastAPI
  - type: web
    name: orquix-backend
    env: python
    region: oregon
    plan: starter
    branch: main
    rootDir: backend
    buildCommand: pip install poetry==2.1.3 && poetry config virtualenvs.create false && poetry install --only=main
    startCommand: chmod +x start.sh && ./start.sh
    healthCheckPath: /api/v1/health
    envVars:
      # Poetry Configuration
      - key: POETRY_NO_INTERACTION
        value: 1
      - key: POETRY_VENV_IN_PROJECT
        value: 1
      
      # App Configuration
      - key: ENVIRONMENT
        value: production
      - key: PROJECT_NAME
        value: Orquix Backend
      - key: PROJECT_VERSION
        value: 1.0.0
      - key: API_V1_STR
        value: /api/v1
      
      # Database - Auto-configured from database service
      - key: DATABASE_URL
        fromDatabase:
          name: orquix-db
          property: connectionString
      
      # Security (CAMBIAR EN PRODUCCIÓN)
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      
      # AI APIs (CONFIGURAR MANUALMENTE)
      - key: OPENAI_API_KEY
        value: CHANGEME_YOUR_OPENAI_API_KEY
      - key: ANTHROPIC_API_KEY
        value: CHANGEME_YOUR_ANTHROPIC_API_KEY
      
      # AI Configuration
      - key: DEFAULT_AI_TIMEOUT
        value: 30
      - key: DEFAULT_AI_MAX_RETRIES
        value: 3
      - key: DEFAULT_AI_TEMPERATURE
        value: 0.7
      - key: DEFAULT_AI_MAX_TOKENS
        value: 1000
      
      # Context Manager Configuration
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: EMBEDDING_DIMENSION
        value: 384
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
      - key: MAX_RETRIES
        value: 3
      - key: RETRY_DELAY
        value: 1
      - key: MAX_CONTEXT_TOKENS
        value: 4000
      - key: CONTEXT_TOKEN_BUFFER
        value: 100
      - key: CONTEXT_SEPARATOR
        value: "\n\n---\n\n"
      
      # Auth (Optional - for future NextAuth integration)
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id_here
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret_here
      - key: JWT_PUBLIC_KEY
        value: your_nextauth_public_key_here

# Base de datos PostgreSQL con pgvector
databases:
  - name: orquix-db
    databaseName: orquix_db
    user: orquix_user
    region: oregon
    plan: standard
    postgresMajorVersion: 15 