"""refactor_interaction_events_to_timeline_v2

Revision ID: ffe4f8b2fa48
Revises: a40f23b782cb
Create Date: 2025-06-20 20:18:44.059919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffe4f8b2fa48'
down_revision: Union[str, None] = 'a40f23b782cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_events', sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('interaction_events', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('interaction_events', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('interaction_events', sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('interaction_events', 'user_prompt_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_interaction_events_event_type'), 'interaction_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_interaction_events_session_id'), 'interaction_events', ['session_id'], unique=False)
    op.drop_constraint(op.f('interaction_events_moderated_synthesis_id_fkey'), 'interaction_events', type_='foreignkey')
    op.create_foreign_key(None, 'interaction_events', 'sessions', ['session_id'], ['id'])
    op.drop_column('interaction_events', 'moderated_synthesis_id')
    op.drop_column('interaction_events', 'ai_responses_json')
    op.drop_column('interaction_events', 'interaction_type')
    op.drop_column('interaction_events', 'moderator_synthesis_json')
    op.drop_column('interaction_events', 'processing_time_ms')
    op.drop_column('interaction_events', 'context_used_summary')
    op.drop_column('interaction_events', 'user_feedback_comment')
    op.drop_column('interaction_events', 'context_used')
    op.drop_column('interaction_events', 'context_preview')
    op.drop_column('interaction_events', 'user_feedback_score')
    op.drop_column('interaction_events', 'session_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_events', sa.Column('session_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('user_feedback_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('context_preview', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('context_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('interaction_events', sa.Column('user_feedback_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('context_used_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('moderator_synthesis_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('interaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('interaction_events', sa.Column('ai_responses_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interaction_events', sa.Column('moderated_synthesis_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interaction_events', type_='foreignkey')
    op.create_foreign_key(op.f('interaction_events_moderated_synthesis_id_fkey'), 'interaction_events', 'moderated_syntheses', ['moderated_synthesis_id'], ['id'])
    op.drop_index(op.f('ix_interaction_events_session_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_event_type'), table_name='interaction_events')
    op.alter_column('interaction_events', 'user_prompt_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('interaction_events', 'event_data')
    op.drop_column('interaction_events', 'content')
    op.drop_column('interaction_events', 'event_type')
    op.drop_column('interaction_events', 'session_id')
    # ### end Alembic commands ###
